language: node_js
sudo: false
node_js:
  - 8
  - 9
  - 10

script:
  - yarn start ./test/fixtures/flow
  # - yarn start ./test/fixtures
  # - yarn start ./test/fixtures -s

before_deploy:
  - npm --no-git-tag-version version `git describe --tags` 2>/dev/null || true

deploy:
  provider: npm
  skip_cleanup: true
  email: oopinou@gmail.com
  api_key:
    secure:
      sfjHFgCIYbFxExyVwbAvAY54DRmyMcy3uPuQIczhSBA3T5554jfGsRlrLO3u/OcVoPPacFmDwLWa7Vlftcfsa2mh5yCryXUrFDVpmHnkWAAADFHjNVwfLR/J2EZAXCaqBMcm6Jwhrhxgk7AsAtLJsTo69uN8+nIbhp2dojneYg1hsEMyVktco30bf3BTSzIvHZ7f/aZZr8gRq1NXSjpHO19UuyxXFbzFB5KK3MJr0TKu4QO8iCUQTth5XueQsxR6fa7efymcurC2u4nMz969WdnMGooJ1kFXx7cu4CZNkVtJLZMdmrZJNldr/CdMUzniaEOAeomj+Ul0gYDIe4FcQ/hKFSwZ8xa9kZ7ImixAeJMoJfQdTeRGGTPQ7l7k/U4fHX8IWYp43njHHTBNmwDbNHmGVU9dsKLx2WKpYt+PvvrpmInpB0LBBsp/QLQhXaGJ4TK0uc2lalYbysFrSARyadFkITpdC2pgh7PB0rQrct6avmCZx8UL4CwWG1zjPe00RBBRW22z+1p1PYvbYeZ0bG7xAW8tHBkvqZJ+vlxGfSd4+l2VUkSu66GNPQL4RvGdoUUI3gSepfDY3JuqKy777aivJTLJHNEhBJQVhZEiyuq6MVwkitxS0V3nwY18mOebIOSQE1h4+Am38FfKN9sivjTm6PyXflZFn4UYLUUn3EQ=
  on:
    tags: true
    repo: DavidBabel/check-flow-annotation
